#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

shopt -s extglob

main() {
  for image_dir in */*; do
    echo "Generating Dockerfile for image $image_dir"
    version="${image_dir%/*}"
    variant="${image_dir##*/}"
    base="${variant%-*}"
    variant="${variant/debian?(-)/}"
    base_image_tag="$([[ -z "$variant" ]] && echo "$version" || echo "$version-$variant")"
    # shellcheck disable=SC2016
    SUBST_BASE_IMAGE_TAG="$base_image_tag" SUBST_RTMP_VERSION=1.2.1 \
      envsubst '$SUBST_BASE_IMAGE_TAG:$SUBST_RTMP_VERSION' < "Dockerfile-$base.template" > "$image_dir/Dockerfile"
  done
}

main "$@"
