#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

shopt -s extglob

LATEST_RTMP_VERSION="$(
  git ls-remote --tags --refs --sort='-v:refname' 'https://github.com/arut/nginx-rtmp-module' 'v*.*.*' | \
  head -1 | cut -d/ -f3 | cut -c2- || test "$?" -eq 141
)"

update_dockerfiles() {
  for image_dir in */*; do
    echo "Updating Dockerfile in ${image_dir}"
    image_version="${image_dir%/*}"
    image_variant="${image_dir##*/}"
    image_variant_short="${image_variant/debian?(-)}"
    base_image_tag="${image_version}"
    if [[ -n "${image_variant_short}" ]]; then
      base_image_tag+="-${image_variant_short}"
    fi
    image_distro="${image_variant/-*}"
    # shellcheck disable=SC2016
    SUBST_BASE_IMAGE_TAG="${base_image_tag}" \
    SUBST_RTMP_VERSION="${LATEST_RTMP_VERSION}" \
    envsubst '${SUBST_BASE_IMAGE_TAG},${SUBST_RTMP_VERSION}' < "Dockerfile-${image_distro}.template" > "${image_dir}/Dockerfile"
  done
}

update_docs() {
  echo "Updating docs"
  # shellcheck disable=SC2016
  SUBST_RTMP_VERSION="${LATEST_RTMP_VERSION}" \
  SUBST_RTMP_MINOR_VERSION="${LATEST_RTMP_VERSION/%.+([0-9])}" \
  SUBST_RTMP_MAJOR_VERSION="${LATEST_RTMP_VERSION//.+([0-9])}" \
  envsubst '${SUBST_RTMP_VERSION},${SUBST_RTMP_MINOR_VERSION},${SUBST_RTMP_MAJOR_VERSION}' < README.template > README.md
}

main() {
  update_dockerfiles
  update_docs
  echo -n "${LATEST_RTMP_VERSION}" > VERSION
}

main "$@"
