#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

shopt -s extglob

RTMP_VERSION=1.2.2

update_dockerfiles() {
  for image_dir in */*; do
    echo "Updating Dockerfile for image ${image_dir}"
    version="${image_dir%/*}"
    variant="${image_dir##*/}"
    base="${variant/-*}"
    variant="${variant/debian?(-)}"
    base_image_tag="$([[ -z "${variant}" ]] && echo "${version}" || echo "${version}-${variant}")"
    # shellcheck disable=SC2016
    SUBST_BASE_IMAGE_TAG="${base_image_tag}" \
    SUBST_RTMP_VERSION="${RTMP_VERSION}" \
    envsubst '${SUBST_BASE_IMAGE_TAG},${SUBST_RTMP_VERSION}' < "Dockerfile-${base}.template" \
      > "${image_dir}/Dockerfile"
  done
}

update_docs() {
  echo "Updating docs"
  # shellcheck disable=SC2016
  SUBST_RTMP_VERSION="${RTMP_VERSION}" \
  SUBST_RTMP_MINOR_VERSION="${RTMP_VERSION/%.+([0-9])}" \
  SUBST_RTMP_MAJOR_VERSION="${RTMP_VERSION//.+([0-9])}" \
  envsubst '${SUBST_RTMP_VERSION},${SUBST_RTMP_MINOR_VERSION},${SUBST_RTMP_MAJOR_VERSION}' \
    < README.template > README.md
}

main() {
  update_dockerfiles
  update_docs
}

main "$@"
