name: deploy

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branch: master

env:
  DOCKER_REPO: vallahaye/nginx-rtmp

defaults:
  run:
    shell: bash

jobs:
  build-push:
    strategy:
      matrix:
        build:
          - tag: mainline
            file: ./mainline/debian/Dockerfile
            platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/mips64le,linux/ppc64le,linux/s390x
          - tag: mainline-perl
            file: ./mainline/debian-perl/Dockerfile
            platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/mips64le,linux/ppc64le,linux/s390x
          - tag: mainline-alpine
            file: ./mainline/alpine/Dockerfile
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          - tag: mainline-alpine-perl
            file: ./mainline/alpine-perl/Dockerfile
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          - tag: stable
            file: ./stable/debian/Dockerfile
            platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/mips64le,linux/ppc64le,linux/s390x
          - tag: stable-perl
            file: ./stable/debian-perl/Dockerfile
            platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/mips64le,linux/ppc64le,linux/s390x
          # Does not target the linux/386 platform on stable Alpine (3.14) builds of NGINX as there is no x86 build of Mercurial available in the repositories
          - tag: stable-alpine
            file: ./stable/alpine/Dockerfile
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          - tag: stable-alpine-perl
            file: ./stable/alpine-perl/Dockerfile
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        run: |
          echo "CURRENT_DATE_TIME=$(date --iso-8601=seconds)" >> $GITHUB_ENV
          echo "RTMP_VERSION=$(<VERSION)" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image tags
        id: build-image-tags
        run: |
          shopt -s extglob
          image_tags=(
            "${DOCKER_REPO}:${DOCKER_TAG}"
            "${DOCKER_REPO}:${RTMP_VERSION}-${DOCKER_TAG}"
            "${DOCKER_REPO}:${RTMP_VERSION/%.+([0-9])}-${DOCKER_TAG}"
            "${DOCKER_REPO}:${RTMP_VERSION//.+([0-9])}-${DOCKER_TAG}"
          )
          if [[ "${DOCKER_TAG}" == "mainline" ]]; then
            image_tags+=("${DOCKER_REPO}:latest")
          fi
          (IFS=,; echo -n "::set-output name=result::${image_tags[*]}")
        env:
          DOCKER_TAG: ${{ matrix.build.tag }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            "RTMP_VERSION=${{ env.RTMP_VERSION }}"
            "OCI_IMAGE_CREATED_AT=${{ env.CURRENT_DATE_TIME }}"
          context: .
          file: ${{ matrix.build.file }}
          platforms: ${{ matrix.build.platforms }}
          push: true
          tags: ${{ steps.build-image-tags.outputs.result }}
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
